ARCO-167: refactor arc.yaml
bitcoin-sv/arc pull request #608
Opened 2024-10-11 14:24 UTC by pawellewandowski98

## Description of Changes

Refctor and update arc.yaml, regenerate api

## Linked Issues / Tickets

ARCO-167

## Testing Procedure

Describe the tests you've added or any testing steps you've taken.

- [ ] I have added new unit tests
- [ ] All tests pass locally
- [ ] I have tested manually in my local environment

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have updated `CHANGELOG.md` with my changes

2024-10-14 10:18 UTC, kuba-4chain commented on pkg/api/arc.yaml
> +#          nullable: false
Remove comment

2024-10-15 14:53 UTC, boecklim requested changes
You should also run `make docs` which will generate a couple of documentation files based on `arc.yaml`

2024-10-16 10:03 UTC, pawellewandowski98 commented on pkg/api/arc.yaml
> -    Callback:
Done, reverted changes

2024-10-16 14:43 UTC, boecklim approved these changes

2024-10-17 06:23 UTC, merged